### ISSUE TITLE
CHD support not work

### ISSUE THREAD

**Issue by ToniBC** [libretro/yabause#104]
Recently, support for CHD was added in YabaSanshiro and Kronos, but it doesn't load in either, but those same isos do load in Beetle Saturn.

It is not yet fully implemented or validated, or it is an error. As the previous topic was closed I find it strange that it does not work.

Many times it is a compilation problem or you need to approve those changes and add them to the main branch.

Thank you.

**Comment by barbudreadmon** [comment]
I converted a few dumps to CHD using chdman, they all worked. Maybe it's only working with CHDv5 and you are using old CHDv4 format ? Or maybe there is a bug with specific games ? What's the games you are trying to launch ?

**Comment by ToniBC** [comment]
All the games I have are in CHDv5 and I can launch the saturn isos with any emulator (then they don't work) that supports CHD and boot perfectly, Beetle Saturn, Beetle PCE, Beetle PSX HW, Genesis Plus GX, but with Kronos or YabaSanshiro not , stays in the Quick Menu with content error.

The version of Kronos is 1.7.0 6edb3d5 and that of YabaSanshiro is 2.6.8 9d1dea1

That is why I comment that it is rare, the format is not because the rest of emulators as I comment if they load those same years even if they do not work because they are from Saturn, but they load them.

**Comment by barbudreadmon** [comment]
Obviously i didn't try the 2000+ known dumps from saturn, only a few and they all worked, if you don't answer to my question "What are the games you are trying to launch ?", i won't be able to help...

**Comment by ToniBC** [comment]
I am very sorry companion, it was a general problem of Retroarch, the video driver was changed to vulkan and the branches of Yabause do not support it and did not load, but the rest of cores do.

My mistake, I didn't realize, I'm so sorry. Yes they work correctly. Thank you very much for implementing it.

**Comment by barbudreadmon** [comment]
I opened this issue : https://github.com/libretro/RetroArch/issues/9388
