### ISSUE TITLE
Kronos - Polygon Flicker

### ISSUE THREAD

**Issue by Dogway** [libretro/yabause#111]
I updated Kronos to test the CHD support and found an issue that seemingly was old. I tested several versions and the one that works is from 14/05, a few versions before that and all versions after that (tested 24/05 and 30/08) make the polygons flicker.
I don't know what the culprit is since the commit list is blank for those 10 days, but I share a video comparison if you are interested. (I recently updated from a 4670K so might be thread related, who knows...)

_Win7 SP1 x64
4790K GTX 1070
Retroarch 1.7.7 x64_

```
kronos_addon_cart = "4M_extended_ram"
kronos_addon_cartridge = "auto"
kronos_auto_select_cart = "enabled"
kronos_filter_mode = "bicubic"
kronos_force_hle_bios = "disabled"
kronos_meshmode = "disabled"
kronos_multitap_port1 = "disabled"
kronos_multitap_port2 = "disabled"
kronos_opengl_version = "4.5"
kronos_polygon_mode = "perspective_correction"
kronos_resolution_mode = "8x"
kronos_scanlines = "disabled"
kronos_service_enabled = "disabled"
kronos_sh2coretype = "kronos"
kronos_upscale_mode = "none"
kronos_use_beetle_saves = "enabled"
kronos_use_cs = "disabled"
kronos_videocoretype = "opengl"
kronos_videoformattype = "NTSC"
```

Kronos 14/05
https://youtu.be/GmqKpmxIisY
Kronos 24/05 and 30/08
https://youtu.be/bBo9t2o0G5s

**Comment by barbudreadmon** [comment]
We don't deal with upstream issues here, especially renderer ones because it's a huge WIP atm, feel free to re-open it at https://github.com/FCare/Kronos/issues, but i'm pretty sure the issue is known anyway.

**Comment by barbudreadmon** [comment]
Also, i would recommend cleaning up the following core options, they were removed or have outdated values : 
```
kronos_addon_cart = "4M_extended_ram" // Those 2 got merged into kronos_addon_cartridge
kronos_auto_select_cart = "enabled" // Those 2 got merged into kronos_addon_cartridge
kronos_resolution_mode = "8x" // Values for this one are pixel-based now
```

**Comment by barbudreadmon** [comment]
One last thing : give a try to the new "OpenGL CS" video renderer, it's the new renderer that might become the default in the future (its main concept is a rasterizer using compute shaders, it requires OpenGL 4.3+), while it's still kinda early WIP it seems to improve things in this game.

**Comment by Dogway** [comment]
Yes that did the trick, now everything is fine, well some minor polygon alignment issues, but I scale down everything to native in the shader so artifacts get minimized. Burning Rangers freezes Retroarch but I guess it will be eventually fixed.

```
kronos_addon_cartridge = "4M_extended_ram"
kronos_filter_mode = "bicubic"
kronos_force_hle_bios = "disabled"
kronos_meshmode = "enabled"
kronos_multitap_port1 = "disabled"
kronos_multitap_port2 = "disabled"
kronos_opengl_version = "4.5"
kronos_polygon_mode = "perspective_correction"
kronos_resolution_mode = "1080p"
kronos_scanlines = "disabled"
kronos_service_enabled = "disabled"
kronos_sh2coretype = "kronos"
kronos_upscale_mode = "none"
kronos_use_beetle_saves = "enabled"
kronos_use_cs = "enabled"
kronos_videocoretype = "opengl_cs"
kronos_videoformattype = "NTSC"
```

**Comment by barbudreadmon** [comment]
> Burning Rangers freezes Retroarch but I guess it will be eventually fixed.

Thanks about this one, i checked the game this week-end and there were a few memory issues i could help with, idk if it fixes your freezes (those freezes never happened for me) but at the very least the code is safer now. This game has some graphical issues with the CS renderer atm though.

On a sidenote : 
- `kronos_addon_cartridge = "4M_extended_ram"` => i recommend "auto", forcing "4M_extended_ram" will prevent some games from running (mostly capcom & snk)
- `kronos_filter_mode = "bicubic"` => i'm not too sure this setting should be exposed in core options in the first place, because i think RA has its own way to deal with this through shaders and other settings
- `kronos_use_cs = "enabled"` => it doesn't hurt to enable it, however it will be ignored with the new renderer which always use compute shaders anyway

**Comment by Dogway** [comment]
@barbudreadmon with the latest build and your suggestions it finally loads, but it's slow (45fps on a 4790K) and has some issues like no audio and some polygon (pixel?) flicker. To be honest the only kronos version that works for this game goes back to 19th of March.

The latest version also doesn't render (garbage pixels) the bios footnote -Sega Enterprises, Ltd....-
