### ISSUE TITLE
Multitap Support Broken

### ISSUE THREAD

**Issue by DisneyFanatic4** [libretro/yabause#128]
In a recent build (1-2 months), the multitap options are removed from User 1 and User 2 breaking games that support more than 2 players.

**Comment by barbudreadmon** [comment]
Oops, sorry for the late answer, actually i moved them to core options in all 3 cores some months ago.

**Comment by DisneyFanatic4** [comment]
When you say "moved them to core options", how do I now enable multitap?  Previously it was an option under Controls for User 1 and 2.  Is there a new section I enable it?

**Comment by barbudreadmon** [comment]
> Is there a new section I enable it?

Yeah, in core options (`Quick Menu > Options` instead of `Quick Menu > Controls`), the options are called `6Players adaptor in portX`, same as beetle saturn.

**Comment by DisneyFanatic4** [comment]
Perfect, thank you so much!
