### ISSUE TITLE
Windows compilation failed!

### ISSUE THREAD

**Issue by frthery** [libretro/yabause#13]
Hi,

Compilation on windows seems to not working properly:
"x86_64-w64-mingw32-g++" -o yabause_libretro.dll ../yabause/src/osdcore.o ../yabause/src/bios.o ../yabause/src/c68k/c68k.o ../yabause/src/cdbase.o ../yabause/src/cheat.o ../yabause/src/coffelf.o ../yabause/src/cs0.o ../yabause/src/cs1.o ../yabause/src/cs2.o ../yabause/src/debug.o ../yabause/src/error.o ../yabause/src/japmodem.o ../yabause/src/m68kc68k.o ../yabause/src/m68kcore.o ../yabause/src/memory.o ../yabause/src/movie.o ../yabause/src/netlink.o ../yabause/src/peripheral.o ../yabause/src/profile.o ../yabause/src/scsp2.o ../yabause/src/scu.o ../yabause/src/sh2core.o ../yabause/src/sh2idle.o ../yabause/src/sh2int.o ../yabause/src/smpc.o yabause_griffin.o ../yabause/src/c68k/c68kexec.o -static-libgcc -static-libstdc++ -lwinmm  -shared -Wl,--no-undefined -Wl,--version-script=link.T
yabause_griffin.o:yabause_griffin.c:(.text+0xd51): référence indéfinie vers « pthread_mutex_lock »
yabause_griffin.o:yabause_griffin.c:(.text+0xd5f): référence indéfinie vers « pthread_setspecific »
yabause_griffin.o:yabause_griffin.c:(.text+0xd6e): référence indéfinie vers « pthread_mutex_unlock »
yabause_griffin.o:yabause_griffin.c:(.text+0x65e3): référence indéfinie vers « pthread_once »
yabause_griffin.o:yabause_griffin.c:(.text+0x660d): référence indéfinie vers « pthread_mutex_init »
yabause_griffin.o:yabause_griffin.c:(.text+0x661f): référence indéfinie vers « pthread_cond_init »
yabause_griffin.o:yabause_griffin.c:(.text+0x664d): référence indéfinie vers « pthread_create »
yabause_griffin.o:yabause_griffin.c:(.text+0x66e5): référence indéfinie vers « pthread_mutex_destroy »
yabause_griffin.o:yabause_griffin.c:(.text+0x6718): référence indéfinie vers « pthread_cond_destroy »
yabause_griffin.o:yabause_griffin.c:(.text+0x6720): référence indéfinie vers « pthread_mutex_destroy »
yabause_griffin.o:yabause_griffin.c:(.text+0x675e): référence indéfinie vers « pthread_join »
yabause_griffin.o:yabause_griffin.c:(.text+0x6767): référence indéfinie vers « pthread_cond_destroy »
yabause_griffin.o:yabause_griffin.c:(.text+0x676f): référence indéfinie vers « pthread_mutex_destroy »
yabause_griffin.o:yabause_griffin.c:(.text+0x67bb): référence indéfinie vers « pthread_getspecific »
yabause_griffin.o:yabause_griffin.c:(.text+0xd8a): référence indéfinie vers « pthread_key_create »
yabause_griffin.o:yabause_griffin.c:(.text+0x67a1): référence indéfinie vers « sched_yield »
yabause_griffin.o:yabause_griffin.c:(.text+0x67cc): référence indéfinie vers « pthread_cond_wait »
yabause_griffin.o:yabause_griffin.c:(.text+0x67f6): référence indéfinie vers « pthread_cond_signal »
/usr/lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld: yabause_griffin.o: mauvaise adresse de relocalisation 0x0 dans la section «.data»
collect2: erreur: ld a retourné 1 code d'état d'exécution
Makefile:207: recipe for target 'yabause_libretro.dll' failed
make: **\* [yabause_libretro.dll] Error 1

Adding LDFLAGS  -lpthread fix the issue. I don't know if it's the correct way to fix that problem.

Regards.

**Comment by barbudreadmon** [comment]
I re-implemented the threading stuff not so long ago, it builds and works, closing.
