### ISSUE TITLE
[Kronos] Cotton Boomerang (ST-V) & Radiant Silvergun (ST-V) player2 controls not working.

### ISSUE THREAD

**Issue by fastpop72** [libretro/yabause#131]
Both ST-V games works for Player1 but Player2 controls are not mapped.

I use a keyboard to play, correctly mapped through RetroArch.

Thanks.

**Comment by barbudreadmon** [comment]
Weird, it was working in the past (actually i did the implementation in https://github.com/libretro/yabause/commit/b1e39339303aacea575ad0228bfb3740263eab7f), i'll look into this.

**Comment by barbudreadmon** [comment]
I broke it in december 2018, now it's fixed

**Comment by fastpop72** [comment]
Thank you. This week i will test more ST-V games...

**Comment by barbudreadmon** [comment]
FWIW, i already know some of them have non-working controls (vfremix, shienryu, there are probably others), however i couldn't figure out the issue. I'm wondering if those games actually work in mame (our st-v driver was ported from mame).

**Comment by fastpop72** [comment]
Shienryu works quite well in mame... vfremix works with some glitches.

**Comment by barbudreadmon** [comment]
Btw, any other issue with stv should be present in standalone too, so it's better if you directly report them at https://github.com/FCare/Kronos
