### ISSUE TITLE
[Kronos] Cotton 2, Cotton Boomerang, Radiant Silvergun & Guardian Force Player2's third button problem.

### ISSUE THREAD

**Issue by fastpop72** [libretro/yabause#133]
In Cotton 2 and Radiant Silvergun is missing the Button 3 of the Player 2, in Cotton Boomerang and Guardian Force this button is mapped together with Button 2.

@barbudreadmon Sorry, i can't test on standalone because i can't find a compiled one.

**Comment by barbudreadmon** [comment]
Upstream issue, should be fixed after https://github.com/FCare/Kronos/pull/680/commits/4f3e2b66370c41aff13ea8d8dfe68feae4ed64d5 is merged

**Comment by fastpop72** [comment]
Thank you!!!

**Comment by barbudreadmon** [comment]
Closing, it should be available now from libretro buildbot.
