### ISSUE TITLE
Colors messed up again in RetroArch

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/yabause#16]
I believe this is a matter of the pixel format getting detected/converted incorrectly.

**Comment by hizzlekizzle** [comment]
Wait... nvm, it's still fine for me. I just made the issue because some people mentioned it on the forum, though I'm having trouble finding the posts now... Perhaps it's breaking on some platforms and not others? Oh well, I'll close this for now and reopen it if/when I get more details.

**Comment by stevenstrike** [comment]
I have messed up colors on every game using latest RA and yabause on Windows 8.1 x64

**Comment by twinaphex** [comment]
Use the latest nightly, the upcoming 1.2.1 version which will launch today should have this fixed.

**Comment by stevenstrike** [comment]
Using RA Stable 1.2.1, colors are now fixed, good job !
