### ISSUE TITLE
1M/4M Ram Cartridge option not working

### ISSUE THREAD

**Issue by jasondaigo** [libretro/yabause#177]
Are the Ram Options actually implemented? If i fire up a Saturn Game which need a cartridge it doesnt pass the loading screen telling me i need a cartridge. For example Metal Slug or Street Fighter Zero 3. It works in standalone Yabause itself with the Cartridge Option.

**Comment by barbudreadmon** [comment]
Yes, it's implemented in core options

**Comment by jasondaigo** [comment]
but it has no effect for the games. unlike YabaSanshiro core.

**Comment by barbudreadmon** [comment]
Oops, fixed in https://github.com/libretro/yabause/commit/9be109f9032afa793d2a79b837c4cc232cea5929

**Comment by jasondaigo** [comment]
so kind of you. im not building it myself but i will use it on next release.a lot :-)
