### ISSUE TITLE
Serialization and unserialization aren't properly implemented

### ISSUE THREAD

**Issue by Kekun** [libretro/yabause#18]
serialize() and unserialize() expect data buffers as parameters but they are implemented expecting the name of the file where to save/load the data to/from.

Also, serialize_size() isn't properly implemented.

**Comment by Kekun** [comment]
P.S.:If you don't have time to work on it, warn me and I'll do it myself.

**Comment by twinaphex** [comment]
Yes, if you could take the intiative that'd be great.

Other things that could be great to look at:
* Getting the new GL renderer to work in the libretro core. I think it's suppsoed to be compatible with GL3 and GLES3.

**Comment by Kekun** [comment]
I know nothing about GL yet unfortunately, sorry, but I'll have to learn some of it in the next few months to make my frontend support libretro-gl.

**Comment by twinaphex** [comment]
OK, no problem, I guess you could do the serialization bits then which would already help us.
