### ISSUE TITLE
Support for 6 player adapter/multitap

### ISSUE THREAD

**Issue by paulo-fernando-silva** [libretro/yabause#203]
I believe beetle core has support for up to two saturn style multitaps: https://segaretro.org/Saturn_6_Player_Adaptor
But YabaSanshiro core doesn't seem to support more than 2. At least when I enable the first 6 player adapter in the options, in practice the game never detects more than 2 controllers connected. I believe this is a limitation of the actual core, as the standalone android YabaSanshiro also doesn't seem to support more than 2 players. 
Any plans to support it?

**Comment by barbudreadmon** [comment]
Actually, it works in the 3 cores.
Also, sorry to be blunt about this but i don't think you should post issues about the yabasanshiro core here, even if there was actually a bug, i wouldn't look into it, the yabasanshiro core is provided as-is.
