### ISSUE TITLE
Wrong colours on yabasanshiro on RPI4 + hack to fix it

### ISSUE THREAD

**Issue by joolswills** [libretro/yabause#208]
As you may be aware, the colours are wrong on the RPI4 with yabasanshiro.

It seems to need the calcs for the texelFetch calls to be rounded up to work - but I'm not sure the cause, or if it's an issue with the VC6 MESA shader compilation code, or a bug that only manifests on this platform.

My knowledge of this is not great.

Here's a patch to fix it - note that this may not be complete, and I do consider it a hack than a fix. But perhaps it is useful.

https://github.com/RetroPie/RetroPie-Setup/blob/5e97cc038e40661d7f97f9d5a0955ba0773b0da5/scriptmodules/libretrocores/lr-yabasanshiro/01_shader_hack_rpi4.diff

I wondered if it might be related to something like https://stackoverflow.com/questions/40574677/how-to-normalize-image-coordinates-for-texture-space-in-opengl

The shader code is quite hard to follow - conversions from int to float, then back to int - I suspect a reworking of the code may show up the issue more clearly.

I originally added round() calls to fix it, but adding 0.5 is equivalent. And makes for less brackets in the changes. There may be cases I've missed where there are still issues too in the source - but Im posting this here in the hope it will aid someone debugging the issue properly.

**Comment by joolswills** [comment]
Updated patch link above due to EOL issues.

Actually - it's worth mentioning this file and possible others have mixed CR and CRLF line endings  - which is worth cleaning up. Confuses some editors / and means patches need to have mixed line endings too.

**Comment by barbudreadmon** [comment]
> As you may be aware, the colours are wrong on the RPI4 with yabasanshiro.

i am, i was part of the discussion on the retropie forum, do you think you can maybe create a PR for this upstream ? tbh, i would prefer to avoid dealing with them, and having different code from upstream is not something i fancy since it'll cause issues whenever i decide to sync with upstream...

**Comment by joolswills** [comment]
I can create an issue - I'd prefer that over a PR as I don't think this is something that should be accepted code wise as is. But it may be useful.

**Comment by joolswills** [comment]
What's the upstream github of the yabasanshiro code btw? Just to confirm - this repo ? https://github.com/devmiyax/yabause ?

**Comment by barbudreadmon** [comment]
yes

**Comment by barbudreadmon** [comment]
codewise, i think it would be fine if you used some `#ifdef RPI4_COLORHACK` or something

**Comment by barbudreadmon** [comment]
it might also be worth mentioning your hack to the vc6 mesa guys

**Comment by joolswills** [comment]
Yeah - my goal was an upstream MESA report, but I don't have the knowledge of this code and I think they will want a small example to illustrate the issue to do anything - if it is an upstream issue.

**Comment by joolswills** [comment]
Appreciate your help / advice. Thanks.
