### ISSUE TITLE
[yabasanshiro] Odroid-N2 in 64Bits

### ISSUE THREAD

**Issue by jdorigao** [libretro/yabause#217]
I'm not able to use libretro-yabasanshiro (64Bits) on odroid-n2 the emulator crashes when starting and is on a black screen.
I wonder if it has already been tested on this architecture and if not what can I do to help solve this problem?

**Comment by barbudreadmon** [comment]
Nothing in logs ?
Anyway, this core is deprecated and probably won't have any more fixes/updates, it's recommended to use standalone instead.

**Comment by jdorigao** [comment]
https://pastebin.com/raw/K2Mabws8
https://pastebin.com/raw/fw4wypXJ

**Comment by barbudreadmon** [comment]
Try with RetroArch 1.8.8, i'm wondering if it's not some shenanigans related to the context commits that were reverted this week-end

**Comment by Ntemis** [comment]
@jdorigao can you please close this down?
