### ISSUE TITLE
Controls are very laggy or non responsive on the Odroid Go Advance using Yabasanshiro

### ISSUE THREAD

**Issue by shantigilbert** [libretro/yabause#222]
This is a weird issue, it seems the OGA game-pad is extremely laggy or non responsive at all when running Yabasanshiro. if I connect another game-pad, or a keyboard the core is responsive and can be played as usual, 2D games seem to run very well on the OGA except for this small issue. 

The issue does not happen with Yabause, but Yabause is extremely slow on the OGA. 

I tried compiling a few older versions, all the way back to 2.10.2 (or 8d0dbe3150e0b72906753262bc0bb8a2e26f8e98) but the same issue occurs.

I tried it in Lakka, and EmuELEC I could not find any other OGA distro that had Yabasanshiro Saturn core so I am not sure if its something related the OS used or something else. 

I can upload a video if needed.

**Comment by barbudreadmon** [comment]
support has been dropped for this core, use standalone instead
