### ISSUE TITLE
Yaba Sanshiro GLSL version issues.

### ISSUE THREAD

**Issue by iokzero** [libretro/yabause#223]
Using Lakka x86_64 Generic on Intel Iris plus 650 HD graphic (Gen 7 CPU)

Trying to run a Saturn game with Yaba Sanshiro, (The game work under other emulator and is known to work with Yaba Sanshiro)

The Core exist with the following error:
[libretro INFO] PG_NORMAL
[libretro INFO] Compile error in vertex shader. 1
[libretro INFO] Shaderlog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

The iGPU should support all the GLSL listed.

Thanks for looking  into this.

**Comment by barbudreadmon** [comment]
Support for this core has been dropped, use standalone

**Comment by iokzero** [comment]
Just want to clarify, is that only Yaba Sanshiro core got drop
Or Yabause/YabaSanshiro/Kronos all got drop? (assuming this is support issue page for all Saturn Emulation Core base on Yabause)

Thanks,

**Comment by barbudreadmon** [comment]
Only yabasanshiro. Fwiw what you are asking for is basically a complete rewrite, yabasanshiro is compatible only with gles and opengl. Your gpu is only compatible with gles and openglcore. You could use gles but it would require custom builds of both retroarch and yabasanshiro

**Comment by iokzero** [comment]
Thank you so much for the clarification and info

Although I am now very confuse all these OpenGL, OpenGL etension, and OpenGL core. Especially where and how to found out which GPU supported what. LOL

**Comment by barbudreadmon** [comment]
Intel gpus got shitty opengl support, only up to 3.0 or something, yabasanshiro requires 3.3, and 4.3 is recommended

**Comment by iokzero** [comment]
is that a driver issue or something ?because it does said on their website
the iGPU should support up to openGL 4.4

https://www.intel.com/content/www/us/en/support/products/98912/graphics/graphics-for-7th-generation-intel-processors/intel-iris-plus-graphics-650.html

**Comment by barbudreadmon** [comment]
I'm not sure if it's a driver issue or if it only applies to linux, but it supports 4.4 only for openglcore
