### ISSUE TITLE
lr-yabause does not build on raspberry pi os 64 bit

### ISSUE THREAD

**Issue by akamming** [libretro/yabause#225]
Hi,

i tried installing this this core using RetroPie and found out it does not build on on rpi4 with raspberry pi os64 bit.

I get the following error:  "unrecognized command line option ‘-mfpmath=sse’ " 

Already solved it myself with a workaround, but wanted to let you know, so you can make a structural fix for the rpi 4 bases on pi os 64 bit.:
- I did some googling to find out the cause, and i think (but i'm not an expert) this particular flag is causing trouble as ARM cpus do not have the SSE extensions.
- So as i workaround in the Makefile is manually changed line 5 to "HAVE_SSE = 0"  and then i could compile and succesfully run this core on an rpi 4 with Raspberry pi os 64 bit.
and then i could use this core on pi os 64 bit.

**Comment by barbudreadmon** [comment]
That's pointless : 
- you can do that without editing Makefile by adding `HAVE_SSE = 0` to your make command (ask retropie team to modify their build script)
- that core won't run at playable speed on any arm board anyway

**Comment by akamming** [comment]
ah tx.. add HAVE_SSE=0 to the make command works indeed! tx!
