### ISSUE TITLE
Possible 3DS port?

### ISSUE THREAD

**Issue by Haze3ds** [libretro/yabause#23]
I knownits a underpowered system with little opengl support. But how involved would a port to the 3DS be just to see?

**Comment by Enverex** [comment]
Well currently there's no GL acceleration and it doesn't run fast enough on a 6th generation i7 CPU, so probably zero until the core's in a considerably better state.

**Comment by barbudreadmon** [comment]
Not gonna happen, simply unrealistic, 3DS suxx way too hard performance wise. Closing.
