### ISSUE TITLE
Yellow bars show up in "Resident Evil" after recent YabaSanshiro core update

### ISSUE THREAD

**Issue by haojiezhu** [libretro/yabause#233]
After recent update of YabaSanshiro core, I am getting yellow bars in "Resident Evil" right after selecting the character and before the start of opening movie. This happens on a 64-bit Windows laptop with integrated Intel HD 4600 and a phone with Snapdragon 835 and Android 10. Both devices have RetroArch 1.9.0 and use GL as video driver. After I rollback YabaSanshiro core with a backup automatically created on Oct 23rd (v3.4.2 446a59b), these yellow bars no longer show up.

Character selection screen (right before yellow bars show up):

![Resident Evil (USA)-201027-075217](https://user-images.githubusercontent.com/11336033/97306441-7d9cfc80-182c-11eb-9381-5cac72cdad1f.png)

Yellow bars before screen fades to opening movie:

![Resident Evil (USA)-201027-075129](https://user-images.githubusercontent.com/11336033/97306797-f3a16380-182c-11eb-91b1-e639270a893a.png)

**Comment by barbudreadmon** [comment]
tagging @rtissera and @ntemis

**Comment by Ntemis** [comment]
Either of us is the core creators. What @rtissera did was to clean the 3.5 from Android code and push it cleaned  for merging

**Comment by barbudreadmon** [comment]
meaning the issue happens on standalone ?

**Comment by rtissera** [comment]
Probably worth a try

Le mar. 27 oct. 2020 à 16:46, barbudreadmon <notifications@github.com> a
écrit :

**Comment by haojiezhu** [comment]
> meaning the issue happens on standalone ?

I just had chance to try the latest version of Yaba Sanshiro 2 Pro from Google play store. It also has this bug. The old Yaba Sanshiro Pro v3.4.2 (removed from play store now) doesn't have this bug. So I guess this bug is from upstream.

**Comment by barbudreadmon** [comment]
Ok, so that's not a libretro issue, i'll close then, please report this upstream
