### ISSUE TITLE
lr-kronos: black image

### ISSUE THREAD

**Issue by raelgc** [libretro/yabause#235]
Any game that I load using `lr-kronos` in RetroPie (on Ubuntu), displays black image. Only in few moments I can see the image: if I open the Retroarch menu (using a transparent theme), or on Saturn bios boot image Sega copyright.

Otherwise, image is always black. I tried different options, but I think I'm missing something.

**Comment by barbudreadmon** [comment]
Update retroarch or set video driver to "glcore", and it'll be fine.
