### ISSUE TITLE
add Wheel support

### ISSUE THREAD

**Issue by eadmaster** [libretro/yabause#241]
it is available in the original core and it is supported by quite some games as analog input before the 3D control pad was released:
https://www.mobygames.com/attribute/sheet/attributeId,2659/p,23/

**Comment by barbudreadmon** [comment]
Sure, i'll hook this to the kronos and yabause cores. I don't maintain yabasanshiro anymore though.

**Comment by barbudreadmon** [comment]
it was added to both yabause and kronos, i'll close
