### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/yabause#248]
Well could you start to use versions like `Major.Minor.Patch` for your releases & update tags/release somewhat regularly?

**Comment by barbudreadmon** [comment]
dupe

**Comment by SupervisedThinking** [comment]
Well I've opened such an issue for many libretro cores because some tag, some have releases, some have recent ones, some have none at all... it looks like everybody does as he likes and that there is no general rule or concept.
