### ISSUE TITLE
Certain CHDs load to cd player

### ISSUE THREAD

**Issue by echenelly** [libretro/yabause#249]
Many CHDs load to the cd player as if the disk image were corrupt, but the same images load properly when loading as bin/cue.  The same CHDs also work properly when played using the beetle saturn core.

I am submitting the issue here since the same behavior happens on both Kronos and YabaSanshiro core on Windows 10.  I also observed the same behavior on my android phone (Galaxy S8+) using YabaSanshiro.

I haven't yet determined why only certain CHDs have this issue - I would be glad to post any logs or other example information to help debug but I am not sure what to post yet.

I tried experimenting with a CHD that had this issue (Ninpen Manmaru).
bin/cue: loads into game & works great
chdman default settings: no load
chdman double hunksize: no load
chdman no compression: no load

**Comment by barbudreadmon** [comment]
> I also observed the same behavior on my android phone (Galaxy S8+) using YabaSanshiro.

Standalone ? Then you should probably report it at yabasanshiro's github, i backported that chd stuff from there and yabasanshiro's author even got the bounty.

**Comment by echenelly** [comment]
It does happen on standalone.  Closing.
