### ISSUE TITLE
[feature request] cheevos support

### ISSUE THREAD

**Issue by meleu** [libretro/yabause#251]
Some users on the RetroAchievements scene claim that the Yabause core has a much better performance than Beetle Saturn on their lowspec machines.

So, making Yabause compatible with RetroAchievements would be a great addition to the list of supported cores for [Saturn cheevos](https://retroachievements.org/gameList.php?c=39).

**Comment by Jamiras** [comment]
All you probably have to do is to expose the memory (either via `retro_get_memory_data`/`retro_get_memory_size` or through `RETRO_ENVIRONMENT_SET_MEMORY_MAPS `).

RetroAchievements is expecting a total of 2MB of system RAM to be exposed - 1MB of Work RAM Low at $200000, and 1MB of Work RAM High at $6000000. If exposing via `retro_get_memory_data`, they should be in one contiguous block (as is done [in Beetle Saturn](https://github.com/libretro/beetle-saturn-libretro/blob/master/libretro.cpp#L156)).

**Comment by Darknior** [comment]
For sure, this emulator the best one, Beetle use a lot of power, little boards can't use it, and Cheevros are really so cool :)

**Comment by barbudreadmon** [comment]
i believe the following code should do the trick : 
```
void *retro_get_memory_data(unsigned id)
{
   if (id == RETRO_MEMORY_SYSTEM_RAM)
   {
      u8 *Wram = calloc(0x200000, sizeof(u8));
      memcpy(Wram, LowWram, 0x100000);
      memcpy(Wram+0x100000, HighWram, 0x100000);
      return Wram;
   }
   return NULL;
}

size_t retro_get_memory_size(unsigned id)
{
   return id == RETRO_MEMORY_SYSTEM_RAM ? 0x200000 : 0;
}
```

Maybe someone could test it before i commit it ?

**Comment by Jamiras** [comment]
I'm doubtful that will work. You're creating a snapshot of the memory, so it won't pick up changes as the program executes (which is very important for triggering achievements). Additionally, it's never free'd, and subsequent calls to this method would allocate more never free'd blocks.

Since you're working with two (presumably non-contiguous) blocks of memory, you're better off using the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` functionality. Have one block claim to start at 0x00200000, and point at `LowWram`. Have the other block claim to start at 0x06000000, and point at `HighWRam`.

**Comment by barbudreadmon** [comment]
@Jamiras do you have an example of `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` usage ?

**Comment by barbudreadmon** [comment]
I found an example, i believe it'll be ok with https://github.com/libretro/yabause/commit/ee6527861c9df370cbbfdaa1a184a762d6f44e0b ? If so i'll probably add this to the Kronos core too

**Comment by Jamiras** [comment]
From a cursory glance, that looks correct.

**Comment by ecloud424** [comment]
Good afternoon to all, is possible to add  retroachievements saturn cheevos compatibility also on yabasanshiro and kronos?
Thank you very much!

**Comment by barbudreadmon** [comment]
@ecloud424 I'm still waiting for confirmation that it is working for yabause before backporting this to Kronos. 
Also, i won't write a single line of code anymore for yabasanshiro.

**Comment by ecloud424** [comment]
@barbudreadmon  I've tried today to load a game in retro archi (Panzer dragoon) with yabause and the achievement system seems to be working. 
I will try to unlock some achievements and I'll let you know if it works

**Comment by ecloud424** [comment]
@barbudreadmon I've unlocked three achievements with yabause in fighters megamix, so the code in yabause works.

**Comment by barbudreadmon** [comment]
Thanks for the heads-up, it'll be available in Kronos soon.

**Comment by ecloud424** [comment]
You're welcome, please let me know if you need some other tests

**Comment by meleu** [comment]
yeah, many RetroAchievements users confirmed that cheevos are working fine with yabause.

I'm closing this issue /request as solved/implemented.

Thanks @barbudreadmon for this work! ❤️

**Comment by barbudreadmon** [comment]
btw, that support was also added to Kronos a few weeks ago
