### ISSUE TITLE
Yabasanshiro on Libretro Android Suddenly Not Working.

### ISSUE THREAD

**Issue by vus7294** [libretro/yabause#253]
[errorlog.txt](https://github.com/libretro/yabause/files/6506536/errorlog.txt)
Here is my Errorlog. i Have saturn_bios.bin(Hi-Saturn Bios and I Used always this) and Trying to boot CHD V5 File and Black Screen and Freeze. Nothing Happened and mentioned Stopped to Working.

**Comment by barbudreadmon** [comment]
I stopped maintaining that core because i don't like how yabasanshiro standalone handles yabause's GPL license, but maybe someone will want to look into this. Also, with the core not being updated anymore, my guess would be that some change in RetroArch caused this issue.

**Comment by emersonnovais** [comment]
Yabasanshiro is the only Saturn core that runs at good speed in my PC. :(

**Comment by barbudreadmon** [comment]
@emersonnovais You can use its standalone version or whatever you want. Again, yabasanshiro is dodgy about yabause's GPL license, so i'm not gonna provide any support anymore for it.
