### ISSUE TITLE
Feature Request - Variable Frame Skip

### ISSUE THREAD

**Issue by KMFDManic** [libretro/yabause#256]
@barbudreadmon Exceptional work, as always!  In any case, many platforms, unfortunately...cannot use Yabasanshiro.  And, they are limited to just standard Yabause with the broken dynarec.  In testing, I am finding many games will far better benefit, if frameskip is variable.  I tested many values between 1+.  The values that will be most optimal to be set as a Core Option would be 0-9.  Nothing higher than that is really needed, as far as what I did test with.  I will throw up a "test" video in next day or so, showing some of the games running at variable rates, which much better handle them in those particular instances.  Shinobi Legions is not remotely playable at "default" frameskip value of 9.  The "last" video I showcased a little of the variables was at:

https://www.youtube.com/watch?v=F3wZXPJdPAg&t=58s

I will do another video.  I definitely feel this will be a nice change for those on lower than open gl 3 platforms.  Thanks for your perusal and continued work in the Scene!

**Comment by barbudreadmon** [comment]
I'm kinda confused here, yabause already has variable frameskip afaik.

**Comment by KMFDManic** [comment]
@barbudreadmon I had forgotten I had already opened and closed an issue regarding this a couple months ago.  But, as a refresher:

FrameSkip can be toggled On/Off (unfortunately, not variable) in Core Options.  Default FrameSkip Value is set to 9.  This stuff was added "sooo long" ago, it can be a little offputting, analyzing the code base...where this stuff all comes to be.  Since this is likely not a high priority, I will dig into the coding a bit more, see if it can feasibly be done as variable rather than toggled on/off, with default value of 9.  If I succeed, anytime soon, I will do a pull request.  It would be beautiful if dynarec even worked with the non yabasanshiro yabause.  But, alas, this at least is an alternative method to get more games somewhat decently playable!  I have a few ideas of how to possibly go about this, and will play around:)  Shame some of the guys who originally worked on the coding do not appear to be active on Github anymore!

**Comment by barbudreadmon** [comment]
@KMFDManic well, i took a look again, the frameskip code really does look like variable frameskip to me, and the 9 value looks like an upper limit for the number of frames that can be skipped consecutively.
If you feel like revisiting that code anyway, good luck, just try to keep the old code and use some `#if __LIBRETRO__` for the new code.

also, i think the cached interpreter from kronos might be more portable to yabause than yabasanshiro's drc
