### ISSUE TITLE
Updates from uoYabause

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/yabause#27]
Is there anything that would fundamentally prevent uoYabause's enhancements from working with libretro?

**Comment by hizzlekizzle** [comment]
I believe most of the enhancements are in the hardware renderer while we only use the software renderer. It would probably make more sense to rebase than to backport.

**Comment by barbudreadmon** [comment]
We have a YabaSanshiro (previously uoYabause) nowaday, closing.
