### ISSUE TITLE
(Windows) Save States require Run as Administrator

### ISSUE THREAD

**Issue by Jamiras** [libretro/yabause#275]
When I try to create a save state using this core, I get an error message indicating the core does not support save states:

![image](https://user-images.githubusercontent.com/32680403/133694639-5f7fba3f-ad47-45cb-b3f7-16a037be8542.png)

If I run RetroArch as Administrator, it works fine.

![image](https://user-images.githubusercontent.com/32680403/133695229-a4f1921c-4ac0-4c33-b726-10569f2da20c.png)

I believe the issue is that `tmpfile` attempts to write to the root directory, which requires elevated permissions (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tmpfile?view=msvc-160)
> The temporary file is created in the root directory.

> This example requires administrative privileges to run on Windows Vista.

If `tmpfile` fails, `size` will be returned as 0.

https://github.com/libretro/yabause/blob/1e33fcad8f9bc7520e61f650e79d6e48ce163178/yabause/src/memory.c#L1306-L1310

Additionally, this implementation is very inefficient as `retro_serialize_size` has to generate a temp file just to determine how big of a buffer to allocate. Then `retro_serialize` generates a second temp file to populate the buffer. It would be preferable to not generate any files for this process, but I understand that's a much larger change.

**Comment by barbudreadmon** [comment]
You are exactly right, this is why i added a fix to prevent crash in https://github.com/libretro/yabause/commit/72ba152a1f987f825182df909e197e95b120ed01 .

You might be interested in backporting my full savestate rework from Kronos, i won't backport it myself, this is too much work for a project that was abandonned by upstream : 
https://github.com/libretro/yabause/commit/9c69108b00d8e0bc6916c6dfbeefb24a30b98e01
https://github.com/libretro/yabause/commit/07dce24c9c738a8925c0a108f2601a6b92f69908
https://github.com/libretro/yabause/commit/4e3761f9b3b5e4f9b9b8e39bbf60d47f928549df

**Comment by barbudreadmon** [comment]
@Jamiras let me know if you intend to backport my work, otherwise i'll close, since i'm pretty much the only contributor here and i won't do that backport.

**Comment by Jamiras** [comment]
I've backported the highlighted commits (thanks for identifying them).

I did notice this while I was in there: 
The buffer allocated for loading the state is never free'd.
https://github.com/libretro/yabause/blob/1885dd2539aa31a5def90d033d9ea37b2b47049a/yabause/src/sys/memory/src/memory.c#L1944

I'm also concerned this change isn't like-for-like:
https://github.com/libretro/yabause/commit/07dce24c9c738a8925c0a108f2601a6b92f69908#diff-81e3755771ca603b5199ee512c2f5fb70ef2bef8446f9f883308ab1a4f64d304L1037

**Comment by barbudreadmon** [comment]
You are right about the buffer, i'll send a fix upstream

> I'm also concerned this change isn't like-for-like:

What do you mean ?

**Comment by Jamiras** [comment]
> What do you mean ?

`SEEK_CUR` moves the pointer from the current location, `MemStateSetOffset` is an absolute position (the equivalent of `SEEK_SET`).

**Comment by barbudreadmon** [comment]
Shit, i didn't notice ! Lucky for us, this is backward compatibility code to support an earlier savestate format (from 2007 iirc), so i guess no one will actually be affected.
