### ISSUE TITLE
Nvidia Shield TV: Yellow striped screen on boot

### ISSUE THREAD

**Issue by Roet-Ivar** [libretro/yabause#28]
I'm using the Nvidia Shield TV and the latest Yabause libretro-core for android.
All I ever see when trying to boot anything on the emulator is a frozen yellow striped screen.
The core information shows BIOS present.

Any idea what's going on?

**Comment by hizzlekizzle** [comment]
I don't know what could be going on specifically, but I will warn that Yabause is one of the slowest cores we have, so I don't think it will reach full speed on a Shield.

**Comment by barbudreadmon** [comment]
Standard yabause core won't run well on Nvidia Shield TV in the first place, the YabaSanshiro core is what you want to use on this device. Closing.
