### ISSUE TITLE
Screen with yellow glitches on Android

### ISSUE THREAD

**Issue by MarlonPxL** [libretro/yabause#282]
![Screenshot_20211031-090948_RetroArch](https://user-images.githubusercontent.com/93597875/139863017-f172854b-3e6e-4253-bc2d-2c0305247e4f.jpg)

**Comment by barbudreadmon** [comment]
**Read first**
This repository is home to 3 libretro cores : yabause, Kronos, and yabasanshiro. Your issue will be closed if you don't mention the core you are using.
