### ISSUE TITLE
YABAUSE - Screen with yellow glitches on Android

### ISSUE THREAD

**Issue by MarlonPxL** [libretro/yabause#283]
![Screenshot_20211031-090948_RetroArch](https://user-images.githubusercontent.com/93597875/139916934-06bd783f-fc6e-44ec-82ec-7f4fde10c77e.jpg)

**Comment by barbudreadmon** [comment]
Might be fixed with https://github.com/libretro/yabause/commit/811f9e81dbff4bed18644e19631fd4893e73e6ee

**Comment by barbudreadmon** [comment]
No confirmation, i'll assume it is fixed, closing.
