### ISSUE TITLE
[YabaSanshiro] Worse performance

### ISSUE THREAD

**Issue by SamuEDL** [libretro/yabause#286]
Good afternoon, I have recently been testing the Emuelec 4.4 test and I have appreciated that the latest version of the core of retroarch: Yabansanshiro, the performance worsened. Instead, with an earlier version (Commit: 7ae0de7abc378f6077aff0fd365ab25cff58b055)  it works correctly.
If it helps, the device where it has been tested is a TVbox with S905x3 with 4GB of RAM.

I attach two videos, so you can compare performance:
Last version: https://www.youtube.com/watch?v=u6o3IOi6fJA
Version commit (7ae0de7abc378f6077aff0fd365ab25cff58b055):  https://www.youtube.com/watch?v=UROvE5Lgcvc

Thanks and sorry for bothering.

**Comment by barbudreadmon** [comment]
>the yabasanshiro libretro core is unmaintained, full of bugs, and shouldn't be used, but contributors who are willing to change that status are welcome

That's the text you apparently deleted without reading when opening this issue
