### ISSUE TITLE
Compiling Yabause on windows/Visual studio

### ISSUE THREAD

**Issue by albertofustinoni** [libretro/yabause#29]
I have recently managed to compile Yabause and get it to run as a WinRT dll using Windows/Visual Studio.

Sadly, though, while `retro_load_game()` seems to work and returns true the core only outputs a black screen and no sound. `retro_run()` causes callbacks to be called as normal but `retro_video_refresh()` always has a black framebuffer.

If possible, I'd like to ask a few questions to do some sanity checking of my setup.

first of all, are the following pre-processor definitions the right ones for building the core for Libretro on Windows?

```
WIN32
HAVE_STRICMP
HAVE_STDINT_H
_CRT_SECURE_NO_WARNINGS
__LIBRETRO__
SIZEOF_DOUBLE=8
USE_16BPP=1
USE_RGB_565=1
USE_SCSP2=1
NO_CLI
HAVE_SYS_TIME_H
VERSION="0.9.12"
HAVE_STRCASECMP
INLINE=inline
HAVE_WFOPEN
HAVE_C99_VARIADIC_MACROS
C68K_NO_JUMP_TABLE
C68K_GEN
```

**Comment by barbudreadmon** [comment]
Building fine on the buildbot with msvc2017, so i guess i can close.
