### ISSUE TITLE
EMUELEC 4.6 seg fault

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/yabause#296]
Repository:Yabasanshiro

When running Yabasanshiro on odroid n2+ I'm ending into a seg fault  with following call stack no matter the Retroarch version I use. 

(gdb) info threads
  Id   Target Id                                         Frame
* 1    Thread 0x7f9fd71020 (LWP 14076) "retroarch"       0x0000007f730f6254 in ?? ()
  2    Thread 0x7f9a73f000 (LWP 14080) "retroarch"       0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  3    Thread 0x7f9939f000 (LWP 14082) "mali-mem-purge"  0x0000007f9b9f7810 in clock_nanosleep () from /usr/lib/libc.so.6
  4    Thread 0x7f98b8f000 (LWP 14083) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  5    Thread 0x7f9837f000 (LWP 14084) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  6    Thread 0x7f97b6f000 (LWP 14085) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  7    Thread 0x7f9735f000 (LWP 14086) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  8    Thread 0x7f96b4f000 (LWP 14087) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  9    Thread 0x7f9633f000 (LWP 14088) "mali-utility-wo" 0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  10   Thread 0x7f95b2f000 (LWP 14089) "mali-cmar-backe" 0x0000007f9ba20d90 in ioctl () from /usr/lib/libc.so.6
  11   Thread 0x7f952ff000 (LWP 14090) "mali-hist-dump"  0x0000007f9b9c3f10 in ?? () from /usr/lib/libc.so.6
  65   Thread 0x7f94aef000 (LWP 14169) "retroarch"       0x0000007f9ba1f2d4 in poll () from /usr/lib/libc.so.6
  66   Thread 0x7f70ab3000 (LWP 14174) "retroarch"       0x0000007f9940083c in ScspAsynMainCpuTime () from /tmp/cores/yabasanshiro_libretro.so

other times it ends on 

(gdb) info threads
  Id   Target Id                                         Frame
* 1    Thread 0x7fb5193020 (LWP 20596) "retroarch"       0x0000007f8c4d5254 in ?? ()
  2    Thread 0x7fafb5f000 (LWP 20597) "retroarch"       0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  3    Thread 0x7fae7bf000 (LWP 20599) "mali-mem-purge"  0x0000007fb0e17810 in clock_nanosleep () from /usr/lib/libc.so.6
  4    Thread 0x7fadfaf000 (LWP 20600) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  5    Thread 0x7fad79f000 (LWP 20601) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  6    Thread 0x7facf8f000 (LWP 20602) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  7    Thread 0x7fac77f000 (LWP 20603) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  8    Thread 0x7fabf6f000 (LWP 20604) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  9    Thread 0x7fab75f000 (LWP 20605) "mali-utility-wo" 0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  10   Thread 0x7faaf4f000 (LWP 20606) "mali-cmar-backe" 0x0000007fb0e40d90 in ioctl () from /usr/lib/libc.so.6
  11   Thread 0x7faa71f000 (LWP 20607) "mali-hist-dump"  0x0000007fb0de3f10 in ?? () from /usr/lib/libc.so.6
  34   Thread 0x7fa9f0f000 (LWP 20692) "retroarch"       0x0000007fb0e3f2d4 in poll () from /usr/lib/libc.so.6
  35   Thread 0x7f85ec3000 (LWP 20697) "retroarch"       0x0000007fae8dbf84 in getM68KCounter () from /tmp/cores/yabasanshiro_libretro.so

Yabsanshiro and retroarch are in debug mode.

please I would like help to troubleshoot it as as far as I see the issue is on ScspAsynMainCpuTime and getM68kCounter.
 
thx

**Comment by barbudreadmon** [comment]
One of my test machines when i ported yabasanshiro to libretro several years ago was an odroid n2 (ubuntu with proprietary bifrost drivers), that crash never occured on that setup. FWIW i don't remember testing the core with threaded video enabled in retroarch settings, so i'd recommend disabling it as it's known for causing issues with a number of situations.

I'm not maintaining this core anymore for reasons explained elsewhere and i don't know if some update (yabasanshrio, retroarch or OS) broke it since then. Maybe @rtissera can help you, afaik he is the only contributor to this core nowaday.

**Comment by Kelvfimer** [comment]
I did a further testing and used the binary of the same version of yabasanshiro but from the previous emuelec test release and it works in the latest test release.

I think it should be any dependency that has been updated.

Nevertheless, I will try with the threaded video. thx

**Comment by Kelvfimer** [comment]
@barbudreadmon I think is a RA issue. FBNEO CD is also having the issue but it seems to be fixed in latest RA commit for FBNEO CD but not for Yabasanshiro. Should I report it in RA issues? thx

**Comment by Kelvfimer** [comment]
It is fixed in the latest build with latest RA 1.15.0
