### ISSUE TITLE
Filtering for Textures

### ISSUE THREAD

**Issue by Papermanzero** [libretro/yabause#297]
Is it possible to add filtering options like swanstation/duckstation has. Bilinear, JINC2 etc

**Comment by Papermanzero** [comment]
Did I miss something? The option is not available in libretro. 🫣

**Comment by barbudreadmon** [comment]
Yes, you didn't read the issue template

**Comment by Papermanzero** [comment]
How about linking then the correct repository to the documentation and entry site so that people can find where to report bugs and features?

**Comment by Papermanzero** [comment]
And how about feature request which ONLY affects the libretro core but are implemented in standalone like xbrz filtering?

**Comment by Papermanzero** [comment]
- the Kronos libretro core is directly maintained upstream (https://github.com/FCare/Kronos), all issues should be reported there

I repeat: You should link to the github repository which is related to 😉

**Comment by barbudreadmon** [comment]
>Kronos

Yes, that's the information that is required in the issue template, otherwise it's warning you that your issue will be closed.

**Comment by barbudreadmon** [comment]
The filters aren't implemented in the libretro port of Kronos because they were deemed useless : RetroArch offers both filters and shaders.

**Comment by Papermanzero** [comment]
libretro cannot filter textures 🙄
