### ISSUE TITLE
Android build broken

### ISSUE THREAD

**Issue by fr500** [libretro/yabause#31]
<retrobot> yabause-armeabi: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27403
<retrobot> yabause-armeabi-v7a: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27405
<retrobot> yabause-x86: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27409

**Comment by barbudreadmon** [comment]
Nowaday they are building fine, so i'll close.
