### ISSUE TITLE
Retroarch crashes the 2nd time you run core

### ISSUE THREAD

**Issue by ghost** [libretro/yabause#38]
with latest commit (https://github.com/libretro/yabause/commit/7515b0d593416f98490d4bfff86b533313b6d05c), yabause crashes the second time you load a rom/cdimage.

steps.

```
1. load rom/cdimage. let it a few minutes 
(at least a few loops after the bios boot logo screen).
2. exit core.
3. launch the game again or load another cdimage.
4. retroarch will close/return to desktop
```

1st bad commit: https://github.com/libretro/yabause/commit/b5b5a3790a72f687c68f33187ee8328817237910

tested cdimages Akumajo Dracula and Cotton 2.
Archlinux

**Comment by Tatsuya79** [comment]
I always crash at 1st launch here on win7 x64.
I bisected and ended on that same commit.

@raelgc
Should the answer would be to try [what you said in the comments of that commit](https://github.com/libretro/yabause/commit/b5b5a3790a72f687c68f33187ee8328817237910)?

**Comment by barbudreadmon** [comment]
This one seems to be fixed too, closing.
