### ISSUE TITLE
Windows port. "Failed to open C:\RetroAr...\saves\...xxx.srm:  No such file or directory "

### ISSUE THREAD

**Issue by Chuguevskiy** [libretro/yabause#40]
Hello
. The emulator always gives out a black screen and freezes. When the emulator freezes, the following message is output:
![yabause](https://user-images.githubusercontent.com/400950/33515568-5d2cc4f2-d776-11e7-832e-d2a0580ef1b7.jpg)

**Comment by barbudreadmon** [comment]
Probably not a core issue, previously save files were handled directly by RA using the libretro api (`retro_get_memory_data/retro_get_memory_size` calls). New version uses the save system internal to the emulator, and it's working. Closing.
