### ISSUE TITLE
[Support request] Information about BIOS

### ISSUE THREAD

**Issue by ofry** [libretro/yabause#53]
Please provide more specific information about saturn_bios.bin in https://docs.libretro.com/library/yabause/

(for example: region, version etc)

**Comment by ofry** [comment]
That's because at least 8 different firmware versions exist.

https://tcrf.net/Sega_Saturn

**Comment by barbudreadmon** [comment]
There isn't much to say, any version will work, so pick the one you prefer and rename it to `saturn_bios.bin`, closing.
