### ISSUE TITLE
[Kronos/YabaSanshiro] Bad Graphics on Intel HD

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/yabause#57]
Testing on the YabaSanshiro/Kronos cores, I noticed that the graphics for Saturn games don't look right, stuff like the Sega Saturn logo doesn't render the particle effects. 3D games like Virtua Fighter 2 just don't fare well on Intel's onboard graphics.

Intel HD (Bay Trail)

**Comment by barbudreadmon** [comment]
windows ?

**Comment by arnoldsecret** [comment]
Windows 8.1 x64

**Comment by barbudreadmon** [comment]
As explained in https://github.com/FCare/Kronos/issues/419 , it appears windows intel gpu drivers are buggy, the same computer running on linux would probably render more properly. We have been searching for a workaround.

**Comment by retro-wertz** [comment]
im on the same boat. and i am using linux. 

![Screenshot from 2019-03-31 23-02-26](https://user-images.githubusercontent.com/23315382/55290711-209b5380-5409-11e9-89ca-a69f5b746452.png)

using vulkan (which works with psx hw) both cores wont run at all...

**Comment by barbudreadmon** [comment]
@retro-wertz What's your gpu exactly ? Is yabasanshiro doing better ? Or standalone versions of those emulators ?
There is no vulkan renderer, and i'm not sure there will be (YabaSanshiro started one long ago, but quickly stopped developping it).

**Comment by barbudreadmon** [comment]
Closing, in the first place rendering issues should be reported upstream : 
- Kronos repo : https://github.com/FCare/Kronos
- YabaSanshiro repo : https://github.com/devmiyax/yabause
