### ISSUE TITLE
[Bounty][5$][Kronos/YabaSanshiro] add CHD support

### ISSUE THREAD

**Issue by Dogway** [libretro/yabause#65]
## https://www.bountysource.com/issues/73976608-kronos-yabasanshiro-align-chd-support-with-reference-mednafen_saturn

Admitting that Kronos is forked from Yabause which doesn't support CHD this core is as reference for 3D based Saturn titles as mednanfen_saturn is for 2D ones.
CHD support becoming an staple support in most Retroarch cores I don't see the reason to not implement it, specially when the cores relate to the same system being emulated leading to having the games mixed in 2 different formats.

**Comment by barbudreadmon** [comment]
Will you open a bounty about this ? If not i might as well tag the issue as `wontfix` and close it, because i won't implement it myself and it's unlikely that anyone else will if there is no bounty backing it.

**Comment by eckso** [comment]
Wasn't aware it involved that much work since other cores had it implemented already.
I will have a look how to create a bounty and create one by tomorrow evening if that's ok. Thanks.

**Comment by barbudreadmon** [comment]
> Wasn't aware it involved that much work since other cores had it implemented already.

Most of them through the bounty system, i believe some cores still have some big bounties pending for this support. 
As a matter of fact, it is a niche feature only interesting for people who want to go to the trouble of converting their isos to chd, which is something that requires some reading and some technical knowledge (let's be honest, those 2 conditions prevent a vast majority of users from using it).

**Comment by eckso** [comment]
It's for cosmetics, support cosmetic (align to the rest of cores) and file system cosmetics mainly for visual clarity of multitrack images and HDD space compression. Clearly for romset storage one would use .zip or .7z but for playbility the tendency is to compress to a playable format. I think the only other important system lacking playable compression is 3DS.
I actually lost the few Saturn images I had assuming Kronos had CHD support, there are many niche things in RetroArch, I guess it's a matter of effort/interest bias.

I found some time and created the Bounty [here](https://www.bountysource.com/issues/73976608-kronos-yabasanshiro-align-chd-support-with-reference-mednafen_saturn). Wanted to edit the title and description to adapt it to a less programming oriented base.

**Comment by Enverex** [comment]
> Most of them through the bounty system

Wasn't that just PCSX_Rearmed?

>It's for cosmetics, support cosmetic (align to the rest of cores) and file system cosmetics mainly for visual clarity of multitrack images and HDD space compression. Clearly for romset storage one would use .zip or .7z but for playbility the tendency is to compress to a playable format. 

Optical disks are large, CHD compresses disks significantly. If a disk is compressed in zip or 7z format, it's not usable as-is. If it's in CHD format then not only will it be *smaller* than a ZIP compressed version, it (would be) usable without prior extraction.

**Comment by barbudreadmon** [comment]
> it (would be) usable without prior extraction.

It is already.

**Comment by escalade** [comment]
@eckso 

If you converted to CHD, nothing is lost as you can simply extract to bin/cue format again.

**Comment by barbudreadmon** [comment]
> If you converted to CHD, nothing is lost as you can simply extract to bin/cue format again.

I don't think you'll get the cue though, only the raw DAO dump.

**Comment by escalade** [comment]
You do get the cue, that's what I'm saying :)

https://pastebin.com/32E5JMww

**Comment by Dogway** [comment]
> 
> 
> You do get the cue, that's what I'm saying :)
> 
> https://pastebin.com/32E5JMww

You don't get multi-track bin's

**Comment by barbudreadmon** [comment]
@escalade Maybe i messed up last time i used it then

@Dogway Yes, afaik it only converts to DAO dumps (that's only an issue for people who prefer reference isosets like redump's though)

**Comment by blisstik** [comment]
@barbudreadmon - I see that standalone got merged here but CHD only works for standalone with the latest commits.

**Comment by barbudreadmon** [comment]
@blisstik thanks for letting me know it works, i wasn't sure since i couldn't get it to work with my first attempt at backporting it (somehow the issue was with libretro-common's packaged version of libchdr), i still have a few things to figure out but i should be committing this later today.

**Comment by blisstik** [comment]
Sweet! BTW I used chd v5

**Comment by barbudreadmon** [comment]
Backport done on yabause & yabasanshiro, kronos will follow soon (for this one i'm backporting on standalone first), i also backported from kronos the support for zipped cue+bin to those 2 cores in the process.

**Comment by barbudreadmon** [comment]
All 3 cores now support this, i don't care about the bounty so if @devmiyax wants to claim it, i don't mind. Closing this.
