### ISSUE TITLE
[Support request] Information about BIOS - reopened

### ISSUE THREAD

**Issue by ofry** [libretro/yabause#73]
Related to #53

> 
> (for example: region, version etc)

> That's because at least 8 different firmware versions exist.
> 
> https://tcrf.net/Sega_Saturn

There isn't much to say, any version will work, so pick the one you prefer and rename it to `saturn_bios.bin`, closing.

_Originally posted by @barbudreadmon in https://github.com/libretro/yabause/issues/53#issuecomment-492193624_

Sorry, but not ANY version will work to ANY game of ANY region, so my question is valid.

**Comment by barbudreadmon** [comment]
> Sorry, but not ANY version will work to ANY game of ANY region, so my question is valid.

Do you have any example of a game working with a bios but not with another with this emulator ?

**Comment by ToniBC** [comment]
In the latest version of Kronos, the bios information is incorrect, says that the two bios saturn_bios.bin and stvbios.zip are missing, but they are present. The games load well, so it can be an error when detecting it or they have to be in another folder within the system.

![Kronos Error Bios](https://user-images.githubusercontent.com/45365478/59373390-dbb96480-8d49-11e9-852f-8f6313cc308e.JPG)

**Comment by barbudreadmon** [comment]
@ToniBC they go in their own folder indeed, see https://github.com/libretro/libretro-super/blob/master/dist/info/kronos_libretro.info , it seems RA isn't showing `firmwareX_path`, it only shows `firmware0_desc`

**Comment by ToniBC** [comment]
Thank you very much, it was that. Apparently the route changed with respect to Yabause in this new version.

Now he detects it.

**Comment by barbudreadmon** [comment]
> Thank you very much, it was that. Apparently the route changed with respect to Yabause in this new version.

I use a fallbacks, it first checks this path, then it checks for yabause's bios, then it checks for mednafen's saturn bioses. That's why you could load games anyway.

**Comment by barbudreadmon** [comment]
@ofry closing, if you aren't going to answer when you are asked for precision, don't bother people

**Comment by ofry** [comment]
Sorry for not answering. But I can't answer this question just now.

I can't launch Yabause core at all. When I trying to compile locally all stuff, I got https://github.com/libretro/RetroArch/issues/9006

**Comment by ofry** [comment]
So I delayed it :( Could you reopen this issue?

**Comment by ofry** [comment]
@barbudreadmon

**Comment by barbudreadmon** [comment]
don't build locally then, re-opening this for now but if you don't give me a clear answer quickly, i will close the subject for good.

**Comment by ofry** [comment]
If I got all stuff from buildbot, Yabause core freezes just after trying open any content.

**Comment by barbudreadmon** [comment]
As i said, any bios works for any game in yabause-based cores to my knowledge, if you can't provide me an example where a specific game needs a specific bios, i'll have to close and you'll have to stop opening issues about this. **I already waited 1 month for your answer**.
If you can't launch a single game in yabause-based cores because it freezes, why are you even opening an issue about bios information ? It doesn't make any sense.

**Comment by ofry** [comment]
I opened this issue because of https://github.com/FCare/Kronos/issues/380#issuecomment-450172889

**Comment by barbudreadmon** [comment]
Yeah, exactly, that's the 3rd issue you open about it, and the answer is still the same : any bios will do for any game. Pick whichever you like and rename it to `saturn_bios.bin`.
If you know of a game which needs a specific bios, let me know, otherwise i'll close this issue by tomorrow. I think i've already been pretty patient with you, opening 3 issues about the same stuff and not listening to our answers or inquiring of precision is clearly harassment.

**Comment by ofry** [comment]
@barbudreadmon 

Quote from https://github.com/FCare/Kronos/issues/380#issuecomment-450172889
> Some Bios will only work with US or Japan games.

So my question is mainly about region-lock.

**Comment by barbudreadmon** [comment]
> So my question is mainly about region-lock.

I don't know of any region-lock, i've played games from every region with most of the bioses at https://tcrf.net/Sega_Saturn, and i've settled for the JP 1.0 bios for a long time now (personal taste), i didn't have any issue, not even once. It might be a fluke, idk, until someone points out a game that work only with a specific bios version, i'll consider them all as region-free from yabause's POV.

NB : for whatever reason, the same bioses aren't region free when used in mednafen, so i really think the region-lock mecanism is simply unemulated by yabause-based cores.

**Comment by ofry** [comment]
OK. If region-lock isn't implemented in Yabause, then I close this issue.
