### ISSUE TITLE
Distorted/slowed down sound in PAL mode

### ISSUE THREAD

**Issue by turboboy215** [libretro/yabause#81]
When I run games at 50hz, the audio sounds slowed down and distorted, despite supposedly running at full speed. This for me makes the emulator rather crippled. I understand that this is far from perfect, but I would really like to use this more if specifically the Yaba Sanshiro version fixes this problem. This happens on both PC and Android. Please fix this!

**Comment by barbudreadmon** [comment]
Your message is lacking a lot of important informations : 
- What core are you using ? YabaSanshiro ? This repo is home to 3 cores...
- What's the game and what is his region ?
- What's your hardware ?

**Comment by turboboy215** [comment]
The game is pretty much every game I try to run. Three games in particular that I'm trying to run are Rayman, Resident Evil, and Panzer Dragoon (all EU region). The hardware that I'm running is on two platforms: a Surface Book (Windows PC) and a Google Pixel (Android).

**Comment by barbudreadmon** [comment]
It seems you can't use 50Hz with yabasanshiro (same upstream), it's only working at 60Hz. I removed the core option to select NTSC/PAL.

**Comment by turboboy215** [comment]
Will this ever be fixed/implemented in the future? Video playback is messed up in 60hz mode using these games. I also have a game which doesn't exist as a 60hz version.
Does the original Yabause work with this at all?

**Comment by barbudreadmon** [comment]
> Will this ever be fixed/implemented in the future?

idk, you might open a feature request upstream about this, i don't deal with upstream issue except if i already know how to fix them.

> Does the original Yabause work with this at all?

No, afaik the only yabause-based core properly handling PAL/NTSC is Kronos (NB : iirc there are some PAL games reporting NTSC though, like Panzer Dragoon), i guess @FCare spent time properly implementing it.
