### ISSUE TITLE
[Kronos] Core starts but runs very slow and missing graphics/colors...

### ISSUE THREAD

**Issue by fastpop72** [libretro/yabause#95]
I tested the Kronos core using Debian10 and PC with Core I5, 12GB ram & Intel HD Graphics.

I tried some ST-V roms and here an example of Cotton Boomerang:

![cottonbm-190812-103919](https://user-images.githubusercontent.com/32760152/62856949-90461700-bcf6-11e9-875f-75d92c783214.png)
![cottonbm-190812-103932](https://user-images.githubusercontent.com/32760152/62856954-93410780-bcf6-11e9-80a9-54a1642c0eb2.png)
![cottonbm-190812-103956](https://user-images.githubusercontent.com/32760152/62856968-989e5200-bcf6-11e9-9b77-587e75ffd8b4.png)

PS: the scanlines are from my setup.

**Comment by barbudreadmon** [comment]
Duplicate of https://github.com/libretro/yabause/issues/57
Sorry to say but that's intel driver bugs, and finding workarounds for those isn't really the job of a small team like ours, intel should publish proper driver instead.
For the reference, what's the model of your cpu & gpu exactly ?

**Comment by fastpop72** [comment]
@barbudreadmon I have an Intel I5-2500 with Intel Graphics HD 2000.

I just installed the new Mesa 19.1.2 drivers from testing but the core gives same result. No luck!

**Comment by barbudreadmon** [comment]
> Intel Graphics HD 2000

It seems this gpu doesn't have proper opengl 3.3 support (it's missing a ton of extensions), it has complete opengl 3.0 implementation at best. Kronos requires proper opengl 3.3 implementation (and actually support for anything below opengl 4.3 might be removed in the future). Kronos also requires a gpu with decent performance, from what i see at https://www.videocardbenchmark.net/gpu.php?gpu=Intel+HD+2000 it's not really the case for this gpu.

With this gpu, you'll need a core with a software renderer (so beetle-saturn or standard yabause).

**Comment by fastpop72** [comment]
I tried adding an Nvidia GT710 (OpenGL 4.6) and the graphics display well now! 

Anyway the slowdown is still there but probably is related to my CPU.

Thanks for all the infos!

**Comment by barbudreadmon** [comment]
> Anyway the slowdown is still there but probably is related to my CPU.

Except if it's downclocked, your cpu is totally fine. Your "new" gpu is probably too slow, as i said Kronos requires a gpu with decent performances
